### ISSUE TITLE
im sorry im just confused

### ISSUE THREAD

**Issue by FrankOcean11** [joeyhoer/gifv#2]
im looking for a windows C# self contain program that can convert given video files and make GIF out of em, im not sure as im sorta new to programming in C++ and just learning syntax and libraries for C# and while in google search i typed "self contain windows video to GIF" your github came up but i dont see much source file so im not sure if you pulled it or what?

 i already have my source made up and am simply looking to embed functions i can use to trigger events that can tell my program to take THAT rec video and pass it thru THAT GIF maker and store THAT GIF output in THAT folder with time and date so tha i can have th program later on parse thru it by using those keys/tags "time & date"

**Comment by joeyhoer** [comment]
This is written in a shell scripting language, not C#. It's basically a wrapper around `ffmpeg`.

**Comment by FrankOcean11** [comment]
ah ic so how would i run this program ? i dont see no .exe file and i dont see the ide that i should use to run it on, sorry for my asking but im lost as this is not my prog language Joey

**Comment by joeyhoer** [comment]
It doesn't compile to an `exe` executable file, it doesn't compile to anything. It's a shell script to be run in a Unix operating system. You may be able to get it to run on Windows with [Cygwin](https://www.cygwin.com).
